Notebook
KseniiaSemenova94/notebook pull request #1
Opened 2019-03-13 23:35 UTC by KseniiaSemenova94

2019-03-23 16:21 UTC, AnnaS91 requested changes
Отличная работа, добавила несколько замечаний на доработку

2019-03-23 16:21 UTC, AnnaS91 commented on src/interfaces/Note.java
> +import java.util.Date;
неиспользуемые импорты лучше удалять

2019-03-23 16:21 UTC, AnnaS91 commented on src/classes/NoteImpl.java
> +    private static int noteCounter = 0;
А почему это поле статическое? 
Т.е. если я создам 2 блокнота в своей программе, у меня у второго блокнота первым элементом может быть запись c id 100.  Так и задумывалось?

2019-03-23 16:21 UTC, AnnaS91 commented on src/classes/NoteImpl.java
> +public class NoteImpl implements Note {
всё-таки модели редко делают имплементящими интерфейсы. Если идея с блокнотом и его интерфейсом мне даже нравится, то тут конечно перебор :)

2019-03-23 16:21 UTC, AnnaS91 commented on src/classes/NotebookImpl.java
> +        this.notes = new Note[10];
10 лучше вынести в константу класса, чтобы во-первых сразу из названия понимать, что она означает, и также чтобы в случае необходимости её можно было легко поменять

2019-03-23 16:21 UTC, AnnaS91 commented on src/classes/NotebookImpl.java
> +        this.firstEmptyCell = 0;
и так по умолчанию будет проинициализирован как 0

2019-03-23 16:21 UTC, AnnaS91 commented on src/classes/NotebookImpl.java
> +        Note[] newNotes = new Note[(int) (this.notes.length * 1.5 + 1)];
1.5 лучше вынести в константу

2019-03-23 16:21 UTC, AnnaS91 commented on src/classes/NotebookImpl.java
> +        for (int i = 0; i < this.notes.length; i++) {
а почему переборка по всей длине массива, а не до последнего существующего? Потенциальный источник NPE, потому что вы будете у null вызывать метод getId

2019-03-23 16:21 UTC, AnnaS91 commented on src/classes/NotebookImpl.java
> +        Note[] newNote = new Note[(int) (this.notes.length / 1.3)];
1.3 лучше в константу

2019-03-23 16:21 UTC, AnnaS91 commented on src/classes/Main.java
> +                 replace = owner.replace(" ", "");
а тебе точно нужно удалять пробелы внутри строки? Метод trim() не подойдёт?

2019-03-24 19:57 UTC, KseniiaSemenova94 commented on src/interfaces/Note.java
> +import java.util.Date;
Убрала

2019-03-24 20:02 UTC, KseniiaSemenova94 commented on src/classes/NoteImpl.java
> +    private static int noteCounter = 0;
Поле статическое для создания уникального значения айди для каждой записи, думала использовать UUID, но решила пойти более простым путем. Если бы в программе предусматривалась работа с двумя блокнотами одновременно, то первая запись у второго блокнота с айди 100 могла бы быть вполне допустимой

2019-03-24 20:03 UTC, KseniiaSemenova94 commented on src/classes/NoteImpl.java
> +public class NoteImpl implements Note {
Убрала

2019-03-24 20:03 UTC, KseniiaSemenova94 commented on src/classes/NotebookImpl.java
> +        this.notes = new Note[10];
Сделано

2019-03-24 20:05 UTC, KseniiaSemenova94 commented on src/classes/NotebookImpl.java
> +        for (int i = 0; i < this.notes.length; i++) {
Исправила

2019-03-24 20:11 UTC, KseniiaSemenova94 commented on src/classes/Main.java
> +                 replace = owner.replace(" ", "");
Исправила на метод trim() и доработала логику, owner приравнивается теперь к обработанной методом trim() строке, немного хотела добиться другого эффекта, чтобы оставалось только по одному пробелу между словами. Но сейчас считаю ситуацию не принципиальной, так как я вообще позволяю пользователю называть себя хоть "уццол45fje675оjdfeg", но главное не пустой строкой :)

2019-03-25 06:21 UTC, AnnaS91 approved these changes

2019-04-07 01:25 UTC, merged